---
title: "Getting and Cleaning Data- Readme"
author: "Amanda Ramdass"
date: "10/19/2020"
output: html_document
---
# Getting and Cleaning Data Project- data
Data Zip File Location: [UC Irvine Repo](https://d396qusza40orc.cloudfront.net/getdata%2Fprojectfiles%2FUCI%20HAR%20Dataset.zip "Clicking will download the data")

## Project Goal
1. A tidy data set 
2. A link to a Github repository with your script for performing the analysis 
3. A code book that describes the variables, the data, and any transformations or work that you performed to clean up the data called CodeBook.md. You should also include a README.md in the repo with your scripts. This repo explains how all of the scripts work and how they are connected.
4. Analysis R Script

## Criteria for review

Goal | Item | Link to Item
--- | --- | ---
Analysis R Script |  run_analysis.R |  [R Script Link](https://github.com/AmandaCRamdass/Getting-and-Cleaning-Data-Project/blob/main/run_analysis.R "run_analysis.R")

Tidy Data Set |  Clean Data Set |  [Data Set Link](https://github.com/AmandaCRamdass/Getting-and-Cleaning-Data-Project/blob/main/tidydata.txt "tidyData.txt")

Github Repo | Repo |  [Repo Link](https://github.com/AmandaCRamdass/Getting-and-Cleaning-Data-Project "Click to go to Repo")

Codebook | CodeBook.md |  [Repo Link](https://github.com/AmandaCRamdass/Getting-and-Cleaning-Data-Project/blob/main/CodeBook.md "CodeBook.md")

README | ReadingItNow |  [Repo Link](https://github.com/AmandaCRamdass/Getting-and-Cleaning-Data-Project/blob/main/README.md "README.md")

## Contributors

FirstName | LastName 
--- | --- | ---
Amanda |  Ramdass 
Submit |  Pull Request 

## License

Anyone may contribute after this assignment is turned in and graded. 



